version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /assertion
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /aws
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /terraformer
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /yubikey
    schedule:
      interval: daily
